trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
    - features/*
    - bugfixes/* 
   
      
jobs:
- template: ../pipelinetemplates/buildtest.yml
  parameters:
    SolutionName: 'IronstoneMeta'    
    LocalBuild: true