parameters:
- name: SolutionName  
  default: ''
- name: Build
  default: Release

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:     
      2022:
        poolFlag: 2022
      2021:
        poolFlag: 2021
      2020:
        poolFlag: 2020
  steps:  
  - template: build.yml
    parameters:
      SolutionName: SolutionName
      Build: Build
      PoolFlag: poolFlag

- job: Test
  workspace:
    clean: all
  strategy:
    matrix:     
      2022:
        poolFlag: 2022
      2021:
        poolFlag: 2021
      2020:
        poolFlag: 2020
  timeoutInMinutes: 30
  dependsOn: Build
  pool:
    name: Autodesk
    demands: Civil3d  -equals $(poolFlag)
  steps:      
  - template: build.yml
    parameters:
      PoolFlag: poolFlag
