jobs:
- job: Package
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:     
      2021:
        poolFlag: 2021
      2020:
        poolFlag: 2020
  dependsOn: Test
  steps:      
  - download: current
    artifact: Build $(poolFlag)
  - task: CopyFiles@2
    inputs:
      contents: |
        '$(Pipeline.Workspace)\Build $(poolFlag)\**\bin\**'
        '!**Tests**
      targetFolder: '$(System.DefaultWorkingDirectory)\installpackage'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)\installpackage' 
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim      
      archiveFile: '$(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip'       
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: Install Package $(poolFlag)    