parameters:
- name: SolutionName  
  default: ''
- name: Build
  default: Release

jobs:
- job: Deploy  
  dependsOn: Test
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: none
  - download: current
  - task: DownloadSecureFile@1
    name: nconf
    displayName: 'Download Nuget Config'
    inputs:
      secureFile: 'nuget.config'
  - script: |
      echo Moving $(nconf.secureFilePath) to the root directory $(System.DefaultWorkingDirectory)...
      xcopy $(nconf.secureFilePath) $(System.DefaultWorkingDirectory)       
  - task: NuGetToolInstaller@1
    inputs:      
      checkLatest: true
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Worksapce)/**/*.symbols.nupkg'
      feedsToUse: 'config'
      nugetConfigPath: $(System.DefaultWorkingDirectory)/nuget.config
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'Github'
      repositoryName: 'JPPGroup/${{ parameters.SolutionName }}'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      tagPattern: 'v.*'
      releaseNotesSource: 'inline'
      releaseNotesInline: 'Latest version'
      isDraft: true
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Worksapce)/**/*.symbols.nupkg'      
